name: Backend-Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#on:
#  workflow_dispatch:
jobs:
  #deploy:
    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- name: Deploy to server
        #uses: appleboy/ssh-action@master
        #with:
          #host: ${{ secrets.HOST }}
          #username: ${{ secrets.USERNAME }}
          #port: ${{ secrets.PORT }}
          #key: ${{ secrets.SSHKEY }}
          #script: "cd /var/www/html && git pull"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: restart the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/html/meetMyTech_API/ && ./deploy.sh"
